apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/enable-access-log: "true"
spec:
  rules:
    - host: go-app.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: go-app-service
              servicePort: 80