apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-go-app
  template:
    metadata:
      labels:
        app: go-go-app
    spec:
      containers:
        - name: go-go-app-container
          image: kevinyan001/kube-go-go-app:v0.3
          resources:
            limits:
              memory: "200Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: go-app-storage
              mountPath: /tmp
      volumes:
        - name: go-app-storage
          emptyDir: {}
