apiVersion: v1
kind: Service
metadata:
  name: go-app-headless-svc
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: stat-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: StatefulSet # <-- claim stateful set
metadata:
  name: stat-go-go-app
spec:
  serviceName: go-app-headless-svc # <-- Set headless service name
  replicas: 2
  selector:
    matchLabels:
      app: stat-go-app
  template:
    metadata:
      labels:
        app: stat-go-app
    spec:
      containers:
        - name: go-go-app-container
          image: kevinyan001/kube-go-go-app
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
